### ISSUE TITLE
Tx gain sweep - attribute Error

### ISSUE THREAD

**Issue by mrsavv** [kit-cel/gr-lpwan#3]
Can't run in GNURadio.
What version of usrp firmware are you using?

Generating: '/home/sav/gr-lpwan/examples/dsss/tx_gain_sweep.py'

Executing: /usr/bin/python2 -u /home/sav/gr-lpwan/examples/dsss/tx_gain_sweep.py

[32;1m[INFO] [UHD] [39;0mlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.HEAD-0-ga1b5c4ae
[32;1m[INFO] [B200] [39;0mDetected Device: B210
[32;1m[INFO] [B200] [39;0mOperating over USB 2.
[32;1m[INFO] [B200] [39;0mInitialize CODEC control...
[32;1m[INFO] [B200] [39;0mInitialize Radio control...
[32;1m[INFO] [B200] [39;0mPerforming register loopback test... 
[32;1m[INFO] [B200] [39;0mRegister loopback test passed
[32;1m[INFO] [B200] [39;0mPerforming register loopback test... 
[32;1m[INFO] [B200] [39;0mRegister loopback test passed
[32;1m[INFO] [AD936X] [39;0mPerforming CODEC loopback test... 
[32;1m[INFO] [AD936X] [39;0mCODEC loopback test passed
[32;1m[INFO] [AD936X] [39;0mPerforming CODEC loopback test... 
[32;1m[INFO] [AD936X] [39;0mCODEC loopback test passed
[32;1m[INFO] [B200] [39;0mSetting master clock rate selection to 'automatic'.
[32;1m[INFO] [B200] [39;0mAsking for clock rate 16.000000 MHz... 
[32;1m[INFO] [B200] [39;0mActually got clock rate 16.000000 MHz.
[32;1m[INFO] [CORES] [39;0mPerforming timer loopback test... 
[32;1m[INFO] [CORES] [39;0mTimer loopback test passed
[32;1m[INFO] [CORES] [39;0mPerforming timer loopback test... 
[32;1m[INFO] [CORES] [39;0mTimer loopback test passed
[32;1m[INFO] [B200] [39;0mAsking for clock rate 32.000000 MHz... 
[32;1m[INFO] [B200] [39;0mActually got clock rate 32.000000 MHz.
[32;1m[INFO] [CORES] [39;0mPerforming timer loopback test... 
[32;1m[INFO] [CORES] [39;0mTimer loopback test passed
[32;1m[INFO] [CORES] [39;0mPerforming timer loopback test... 
[32;1m[INFO] [CORES] [39;0mTimer loopback test passed
Traceback (most recent call last):
  File "/home/sav/gr-lpwan/examples/dsss/tx_gain_sweep.py", line 368, in <module>
    main()
  File "/home/sav/gr-lpwan/examples/dsss/tx_gain_sweep.py", line 356, in main
    tb = top_block_cls(chiprate=options.chiprate, data_seed_tx=options.data_seed_tx, dev_addr=options.dev_addr, msg_period_ms=options.msg_period_ms, num_sweeps=options.num_sweeps, ovsf_code_index=options.ovsf_code_index, ovsf_spreading_factor=options.ovsf_spreading_factor, preamble_len=options.preamble_len, preamble_seed_tx=options.preamble_seed_tx, psdu_len=options.psdu_len, roll_off=options.roll_off, spread_factor=options.spread_factor, sps=options.sps)
  File "/home/sav/gr-lpwan/examples/dsss/tx_gain_sweep.py", line 113, in __init__
    self.lpwan_dsss_tx_gain_sweep_0 = lpwan.dsss_tx_gain_sweep(spread_factor, (tx_gains), psdu_len-4, num_sweeps)
AttributeError: 'module' object has no attribute 'dsss_tx_gain_sweep'

**Comment by fwunsch** [comment]
This error has nothing to do with UHD and the USRP. You obviously didn't install the module correctly. Make sure you have SWIG installed when compiling the OOT so that the bindings are generated.

This is no bug, so I'm closing the issue.
